baseURL = 'https://sulphurium.com/'
languageCode = 'en-ca'
title = 'Daniels Blog'
theme = "hugo-blog-awesome"
defaultContentLanguage = "en-ca"
enableEmoji = true

# adds code highlighting
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 1 # ToC starts from H1
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

# favicon
#[params]
#  favicon = "favicon.ico"

# image cache
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Social Icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/varig203"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/daniel-treiber-bobylev-1a99bb354/"

###### ENGLISH ######
[Languages.en-ca]
  languageName = "English (Canada)"
  languageCode = "en-ca"
  contentDir = "content/en-ca"
  weight = 1

# customizing top bar
[Languages.en-ca.menu]
[[Languages.en-ca.menu.main]]
  pageRef = "/"
  name = 'Home'
  url = '/'
  weight = 10
[[Languages.en-ca.menu.main]]
  pageRef = "blogs"
  name = 'Blogs'
  url = '/blogs/'
  weight = 20 
[[Languages.en-ca.menu.main]]
  pageRef = "about"
  name = 'About'
  url = '/about/'
  weight = 30

# site params
[Languages.en-ca.params]
  sitename = "Daniel's Blog"
  defaultColor = "dark"
  goToTop = true
  toc = true
  tocOpen = true
  mainSections = ['blogs']

# author params
[Languages.en-ca.params.author]
  avatar = "avatar.jpg"
  name = "Daniel T-B"
  intro = "Daniel's Blog/Portfolio"
  description = "Everything that Daniel does related to his career in Software Development."

###### German ######
[Languages.de]
  languageName = "Deutsche
  languageCode = "de"
  contentDir = "content/de"
  weight = 2

[Languages.de.menu]
[[Languages.de.menu.main]]
  pageRef = "/"
  name = 'Startseite'
  url = '/'
  weight = 10
[[Languages.de.menu.main]]
  pageRef = "blogs"
  name = 'Blogs'
  url = '/blogs/'
  weight = 20 
[[Languages.de.menu.main]]
  pageRef = "about"
  name = 'Über'
  url = '/about/'
  weight = 30

# site params
[Languages.en-ca.params]
  sitename = "Daniel's Blog"
  defaultColor = "dark"
  goToTop = true
  toc = true
  tocOpen = true
  mainSections = ['blogs']

# author params
[Languages.en-ca.params.author]
  avatar = "avatar.jpg"
  name = "Daniel T-B"
  intro = "Daniel's Blog/Portfolio"
  description = "Alles, was Daniel im Bereich Softwareentwicklung macht."