baseURL = 'https://sulphurium.com/'
languageCode = 'en-us'
title = 'Daniels Blog Site'
theme = "hugo-blog-awesome"

# Social Icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/varig203"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/daniel-treiber-bobylev-1a99bb354/"

# Blog params
[params]
  goToTop = true
